trigger:
  branches:
    - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npx cypress run 
    displayName: 'Run Cypress Tests with JUnit Reporter'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/cypress/results/*.xml'
      failTaskOnFailedTests: true
    condition: succeededOrFailed()
    displayName: 'Publish Test Results'
