trigger:
  - main  # Replace with your desired branch

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'  # Replace with the Node.js version your project uses
    displayName: 'Install Node.js'

  - script: |
      npm ci
    displayName: 'Install dependencies'

  - script: |
      npx cypress verify
    displayName: 'Verify Cypress installation'

  - script: |
      npx cypress run
    displayName: 'Run Cypress tests'
